### ISSUE TITLE
Marking locations inside The Stranger on the HUD doesn't work when this mod is enabled

### ISSUE THREAD

**Issue by serega6531** [xen-42/ow-decloaked#2]
Usually after marking a location inside the ship log you can see little arrows locating them on you hud. However, with this mod locations inside the Stranger no longer appear, whether you're inside it or outside.

**Comment by TrottyMan** [comment]
Seems when this is installed I lose the HUD marker for the Scout & the ship.
Not the biggest problem but cause some confusion in Dark Bramble

**Comment by xen-42** [comment]
Fixed in 1.0.3 (one year later, mb)
